### PR TITLE
Feature/navbar

### PR DESCRIPTION
**Pull request by artrocity**
After initial updates to the file structure so that we could have a working file directory I changed the internal jsx of the main components to give us a "blank" starting space. The following was modified to bring the navbar into a working testing function:

- Modified App.jsx imports
- Modified App.jsx routes
- Modified Nav.jsx javascript, imports and order structure
- Modified CSS Color of the background
- Modified Company Name in the navbar
- Attached the new Navbar to all of the main components (Landing Page, Marketplace, Features, About, Contact, and Login)

### CODE REVIEW

**Review by AlvinGraham — APPROVED** [review]
This all look good and clean to me. I recommend meging.

**Review by jessiyang1996 — COMMENTED** [review]
This looks good to me. Thanks for the hard work!

**Review by jessiyang1996 — APPROVED** [review]
Approving

**Review by ksieracke — APPROVED** [review]
Looks good!

**Pull request merged**
